name: Déploiement Frontend de Forprode

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupérer le code
        uses: actions/checkout@v3

      - name: 🔧 Installer Node.js et les dépendances
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: npm run generate

      - name: 🚀 Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public
          server-dir: /htdocs